allow_anonymous false

listener 1883
protocol mqtt

listener 9001
protocol websockets

auth_plugin /mosquitto/go-auth.so
auth_opt_backends jwt
auth_opt_jwt_secret 5JCjXpDNDJBhHwfrFDSNKNFSDK34543gfojgseogdsfn453453
auth_opt_jwt_files_acl_path /mosquitto/config/acl



persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/