version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/pwfile:/mosquitto/config/pwfile
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log


