services:
  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
        - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
        - ./mosquitto/config/acl:/mosquitto/config/acl
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

