spring.application.name=project
spring.datasource.url=jdbc:postgresql://bkf7jfv8hu63btiipahb-postgresql.services.clever-cloud.com:5432/bkf7jfv8hu63btiipahb
spring.datasource.username=uuae3dhgtv3esql1w1lu
spring.datasource.password=TYZX3rVgtxz5vheAkXIS6YLyGGfBVm
#gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=integradorusta@gmail.com
spring.mail.password=bamk chxf lzex dblt
#porperties
spring.mail.properties.mail.smtp.auth=true
#TLS
spring.mail.properties.mail.smtp.starttls.enable=true
#Mosquitto
mqtt.url=tcp://localhost:1883
mqtt.id=spring-boot-mqtt-client
mqtt.topic=test/topic
#jwt
jwt.secret-key = dfsjhgpoiuyrfdesgopifhdfgssdgf;f
jwt.expiration= 8640000
jwt.refresh = 6440000

